# Generated by Django 5.1.6 on 2025-03-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conventions',
            new_name='Convention',
        ),
    ]
