# Generated by Django 5.1.6 on 2025-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0002_rename_conventions_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='con_type',
            field=models.CharField(choices=[('A', 'Anime'), ('G', 'General'), ('F', 'Furry'), ('C', 'Comic'), ('H', 'Horror')], default='G', max_length=1),
        ),
    ]
