# Generated by Django 5.1.6 on 2025-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0003_convention_con_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
