# Generated by Django 5.1.6 on 2025-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0004_convention_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='image_urls',
            field=models.JSONField(default=['https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/1200px-No_image_available.svg.png']),
        ),
    ]
