# Generated by Django 5.1.6 on 2025-03-23 21:34

import conventions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0005_convention_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='image_urls',
            field=models.JSONField(default=conventions.models.default_image_urls),
        ),
    ]
