# Generated by Django 5.1.6 on 2025-03-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0006_alter_convention_image_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='con_images/')),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='conventions.convention')),
            ],
        ),
    ]
