# Generated by Django 5.1.6 on 2025-03-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0007_conventionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='image_urls',
        ),
    ]
