# Generated by Django 5.1.6 on 2025-03-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0008_remove_convention_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
