# Generated by Django 5.1.6 on 2025-03-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0009_convention_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
