# Generated by Django 5.1.6 on 2025-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0010_convention_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='convention',
            name='num_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='convention',
            name='num_attend',
            field=models.IntegerField(default=1),
        ),
    ]
