# Generated by Django 5.1.6 on 2025-03-30 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0011_convention_image_convention_num_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conventionimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
