# Generated by Django 5.1.6 on 2025-04-03 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0013_favoriteconventiont'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteConvention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('Convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='conventions.convention')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_Conventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'Convention')},
            },
        ),
        migrations.DeleteModel(
            name='FavoriteConventiont',
        ),
    ]
