# Generated by Django 5.1.6 on 2025-04-03 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0014_favoriteconvention_delete_favoriteconventiont'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_cons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoriteConvention',
        ),
    ]
