# Generated by Django 5.1.6 on 2025-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0016_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convention',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='convention',
            name='rating_total',
            field=models.IntegerField(default=0),
        ),
    ]
