# Generated by Django 5.1.6 on 2025-02-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=100)),
                ('con_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('num_attend', models.IntegerField()),
                ('con_type', models.CharField(choices=[('A', 'Anime'), ('G', 'Gaming'), ('C', 'Comic'), ('F', 'Fantasy'), ('FR', 'Furry'), ('H', 'Horror'), ('G', 'General')], max_length=2)),
                ('booth_cost', models.IntegerField()),
                ('travel_cost', models.IntegerField()),
                ('apply_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
